# Generated by Django 4.2.2 on 2023-06-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ecommerce', 'Ecommerce'), ('digital', 'Digital'), ('restaurant', 'Restaurant')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('expense', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('description', models.TextField(max_length=2000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businessapp.category')),
            ],
        ),
    ]
