# Generated by Django 4.2.2 on 2023-06-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='seller',
        ),
    ]
