# Generated by Django 4.2.2 on 2023-06-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0002_rename_name_business_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='img1',
            field=models.CharField(default='sdsd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='img2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
